/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author GP
 */
public class jfrmSoporte extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmSoporte.class.getName());

    /**
     * Creates new form jfrmSoporte
     */
    public jfrmSoporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jblimagen = new javax.swing.JLabel();
        jblNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxDef = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxFun = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(350, 400));

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));

        jblimagen.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jblimagen.setForeground(new java.awt.Color(255, 0, 0));

        jblNombre.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jblNombre.setForeground(new java.awt.Color(255, 0, 0));

        jtxDef.setColumns(20);
        jtxDef.setLineWrap(true);
        jtxDef.setRows(5);
        jtxDef.setWrapStyleWord(true);
        jtxDef.setEnabled(false);
        jScrollPane1.setViewportView(jtxDef);

        jtxFun.setColumns(20);
        jtxFun.setLineWrap(true);
        jtxFun.setRows(5);
        jtxFun.setWrapStyleWord(true);
        jtxFun.setEnabled(false);
        jScrollPane2.setViewportView(jtxFun);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(163, 163, 163)
                    .addComponent(jblNombre)
                    .addContainerGap(165, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblimagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jblNombre)
                    .addContainerGap(235, Short.MAX_VALUE)))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Imagenes");

        jMenuItem4.setText("MotherBoard");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Procesador");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Ram");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Cooler");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Fuente de Poder");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jblNombre.setText("");
        jblNombre.setText("MotherBoard");
        jblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/motherboard.png")));
        jtxDef.setText("La motherboard (o placa base) es la tarjeta de circuito principal de la computadora.");
        jtxFun.setText("Su función es actuar como el sistema nervioso del equipo: conecta físicamente todos los componentes (como el procesador, la memoria RAM y el disco duro), permite que se comuniquen entre sí y distribuye la energía eléctrica para que funcionen juntos.");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jblNombre.setText("");
        jblNombre.setText("Procesador");
        jblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cpu.png")));
        jtxDef.setText("La CPU (o procesador) es el cerebro de la computadora.");
        jtxFun.setText("Su función principal es procesar todos los datos y ejecutar las instrucciones de los programas y del sistema operativo.\n" +
"\n" +
"Básicamente, realiza tres tareas en bucle a una velocidad increíble:\n" +
"\n" +
"Recibe las órdenes que tú le das (como hacer un clic o abrir un juego).\n" +
"\n" +
"Calcula y procesa esa información matemáticamente.\n" +
"\n" +
"Envía el resultado a la pantalla o al componente correspondiente.");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jblNombre.setText("");
        jblNombre.setText("Ram");
        jblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ram.png")));
        jtxDef.setText("La RAM es la memoria a corto plazo de la computadora.");
        jtxFun.setText("Su función es almacenar temporalmente los datos de las aplicaciones que estás usando en el momento (como tus pestañas abiertas o un juego) para que el procesador acceda a ellos al instante.\n" +
"\n" +
"Al ser temporal, se borra por completo cuando apagas la computadora. Cuanta más RAM tengas, más programas podrás abrir al mismo tiempo sin que el equipo se ponga lento.");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        jblNombre.setText("");
        jblNombre.setText("Cooler");
        jblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cooler.png")));
        jtxDef.setText("El cooler es el sistema de enfriamiento de la computadora.");
        jtxFun.setText("Su función es absorber el calor que generan componentes como el procesador y expulsarlo fuera del equipo. Básicamente, evita que tu computadora se sobrecaliente, se vuelva lenta o se dañe por las altas temperaturas.");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        jblNombre.setText("");
        jblNombre.setText("Fuente de Poder");
        jblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fuente.png")));
        jtxDef.setText("La fuente de poder es el corazón energético de la computadora.");
        jtxFun.setText("Su función es recibir la electricidad del enchufe de tu casa (que es corriente alterna) y transformarla en la corriente que tu computadora necesita (corriente continua). Además, se encarga de repartir el voltaje exacto a cada componente (como la motherboard, el procesador y la tarjeta de video) para que puedan encender sin quemarse.");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmSoporte().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jblNombre;
    private javax.swing.JLabel jblimagen;
    private javax.swing.JTextArea jtxDef;
    private javax.swing.JTextArea jtxFun;
    // End of variables declaration//GEN-END:variables
}
